"""add_cpu_mem_to_agent

Revision ID: 1d0d91a240bd
Revises: 01a6f3be8593
Create Date: 2026-01-04 19:37:51.873174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d0d91a240bd'
down_revision = '01a6f3be8593'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('mem', sa.Float(), nullable=True))
    op.alter_column('agents', 'cpu',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('agents', 'memory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('memory', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('agents', 'cpu',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.drop_column('agents', 'mem')
    # ### end Alembic commands ###
